# -*- coding: utf-8 -*-
"""techthella_flask.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GYXIcL-siYOGdr6LuaU_E7C_CoxuQZfS
"""

!pip install pyngrok==4.1.1
!pip install flask_ngrok
from crypt import methods
from pyexpat import features, model
import numpy as np
from flask import Flask, request, jsonify, render_template
import pickle

from google.colab import drive
drive.mount('/content/drive')


!ngrok authtoken 2GCkFbRaeQNefOeHPp6GYZUShI3_2qCYt5fxsqh7k2jqqst4J 

from flask_ngrok import run_with_ngrok
from flask import Flask, render_template
app = Flask(__name__,template_folder='/content/drive/MyDrive/techthella')
model = pickle.load(open('/content/drive/MyDrive/model.pkl','rb'))
run_with_ngrok(app)
@app.route('/')
def text():
  return render_template('index.html')

@app.route('/result',methods=['POST'])
def worker():
    int_features = [int(x) for x in request.form.values()]
    final_features = [np.array(int_features)]
    prediction = model.predict(final_features)

    output = round(prediction[0])
    print(output)

    return jsonify(output)
app.run()